connection:
  indexserver_hostname: hostname  # The indexserver hostname
  indexserver_port: 30015         # The indexserver SQL port
  container_group_admin: USER     # The user with Container Group Administrator
  password: PLAIN_PASSWORD        # The password
  encrypt: False                  # Keep False by default for not SSL-enforced connections
  sslValidateCertificate: False   # Keep False by default

client_config:
  output_dir: ./output
  logging_level: INFO # CRITICAL | ERROR | WARNING | INFO | DEBUG | NOTSET

processing:
  max_concurrency: 3 # The allowed number of parallel operations

operations:
  _SYS_DI#SYS_XS_HANA_BROKER: # The container group name
    delete:                   # The operation to be performed, supported options: delete
      - NAMED_CONTAINER       # The container name